### ISSUE TITLE
Doest work?

### ISSUE THREAD

**Issue by lee-mustard** [bryanwillis/gravityforms-ready-class-selector-revised#1]
Hey man, doesn't seem to be working anymore?

**Comment by bryanwillis** [comment]
I just downloaded and installed again on a new site to see what was going on, but it seems to be working fine for me. I have  WP 4.6.1 installed and Gravity Forms 2.0.7, but I've been using it for for the last 6 months or so with previous version of GF and WP as well.

Is there something specific that's not working or just the whole thing? 

This is what it should look like:

<img width="1245" alt="screen shot 344" src="https://cloud.githubusercontent.com/assets/4042621/18492516/4b9b3c7c-79d1-11e6-81cd-42b90286c616.png">

<img width="1225" alt="screen shot 343" src="https://cloud.githubusercontent.com/assets/4042621/18492520/4f288e3a-79d1-11e6-8268-f9f798ce726a.png">

The things I can think of off the bat since mines working is that the dashicon icon-font is being overridden somehow or possibly is_plugin_active isn't working. You can try changing that out for one of the commented out lines on [line 17](https://github.com/bryanwillis/gravityforms-ready-class-selector-revised/blob/master/gravityforms-ready-class-selector-revised.php#L17).

**Comment by lee-mustard** [comment]
`if ( is_plugin_active( 'gravityforms/gravityforms.php' ) ) {
    add_action('gform_editor_js', 'brw_gf_ready_class_selector_revised_render_editor_js');
}
`

worked when i removed the above (as you suggested)

Thanks man!

**Comment by bryanwillis** [comment]
Thanks I'll change the plugin to reflect this issue. Ironically I asked a question on WPSE back in January about using "is_plugin_active" in another plugin which wasn't working. 

http://wordpress.stackexchange.com/a/216065/38123

I guess `include_once( ABSPATH . 'wp-admin/includes/plugin.php' );` seems to fix the issue a lot of the times, but we're better off just using a gravity forms class or function anyway... If your gravity forms folder gets renamed or something like  `gravityforms-master/gravityforms.php`, which it would if you had it uploaded to github then `is_plugin_active` would never work, which is why it's not a great function to begin with.

**Comment by bryanwillis** [comment]
@lee-mustard 

Lee if you get a chance could you try the revised changes [with this](https://github.com/bryanwillis/gravityforms-ready-class-selector-revised/blob/master/gravityforms-ready-class-selector-revised.php#L17).

It's good that it works when removing that code, but it's probably good to have some sort of conditional check in case gravity forms get deactivated.

**Comment by lee-mustard** [comment]
Will get onto to it.

Thanks man
